### ISSUE TITLE
Minor Request

### ISSUE THREAD

**Issue by luckyguy73** [paritho/tabex#2]
dear sir, i love your extension it's what i have been searching for.  thank you so much for creating this.
i have one minor request please if you can just add small feature to set TabEx On/True/Checked by default.  every time i open brackets i have to turn it on myself and i forget quite often and extra step i'd rather not have since i always want TabEx on.  Thank you kindly.

**Comment by paritho** [comment]
Hi, thank you for your comments! I'm working on this feature as I too find it annoying! Also, I'm working on keeping TabEx active when you switch between files.

**Comment by luckyguy73** [comment]
awesome!  i really look forward to that, and thanks for all your efforts!

```
  From: Paul Thompson <notifications@github.com>
```

 To: paritho/tabex tabex@noreply.github.com 
Cc: ashton luckyguy73@yahoo.com; Author author@noreply.github.com
 Sent: Tuesday, July 26, 2016 6:40 AM
 Subject: Re: [paritho/tabex] Minor Request (#2)

Hi, thank you for your comments! I'm working on this feature as I too find it annoying! Also, I'm working on keeping TabEx active when you switch between files.—

**Comment by paritho** [comment]
Hi, I just wanted to let you know that I've finished this feature (I hope). If you have TabEx on when you close brackets, it should be on when you start it again. It should also stay on if you switch files. The next time you start brackets, look at your extension manager and you should see the option to update TabEx. Thanks!
